[firebase]
apiKey = "AIzaSyDVOeC2q52Q3KMYHJOFGJjKhWupGQjebjo"
authDomain = "eagmapa.firebaseapp.com"
projectId = "eagmapa"
storageBucket = "eagmapa.firebasestorage.app"
messagingSenderId = "193230609942"
appId = "1:193230609942:web:721a5baa965293af19df37"
databaseURL = "https://eagmapa-default-rtdb.firebaseio.com/"